# Generated by Django 3.1.4 on 2021-10-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bloodinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.FloatField(max_length=20)),
                ('param2', models.FloatField(max_length=20)),
                ('param3', models.FloatField(max_length=20)),
                ('param4', models.FloatField(max_length=20)),
                ('param5', models.FloatField(max_length=20)),
                ('param6', models.FloatField(max_length=20)),
                ('param7', models.FloatField(max_length=20)),
                ('param8', models.FloatField(max_length=20)),
                ('param9', models.FloatField(max_length=20)),
            ],
        ),
    ]
