# Generated by Django 3.1.4 on 2021-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20211107_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodinfo_origin',
            name='param6',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodinfo_origin',
            name='param7',
            field=models.FloatField(max_length=20),
        ),
    ]
